---
title: "flat_human_geom_calculation.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

<!--
 You need to run the 'description' chunk in the '0-dev_history.Rmd' file before continuing your code there.
-->

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# Gravity center : gravity_center
    
```{r function-gravity_center}
#' Title
#' 
#' Description
#' 
#' @return
#' 
#' @export
gravity_center <- function(){
    
}
```
  
```{r example-gravity_center}
gravity_center()
```
  
```{r tests-gravity_center}
test_that("gravity_center works", {
  expect_true(inherits(gravity_center, "function")) 
})
```
  

```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_human_geom_calculation.Rmd", vignette_name = "Human Geometry Calculation")
```
