# WARNING - Generated by {fusen} from /dev/flat_human_geom_calculation.Rmd: do not edit by hand

#' Title
#' 
#' Description
#' 
#' @return
#' 
#' @export
#' @examples
#' gravity_center()
gravity_center <- function(){
    
}
